name: Build

on:
  push:
    branches:
      - 1-github-actions-for-running-tests-and-building-the-app

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_artifacts:
    name: Build artifacts
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
            os: windows-latest,
            build_command: cargo build --release,
            artifact_name: "clock-windows",
            artifact_path: "clock.exe"
          }
          - {
            os: ubuntu-latest,
            command: sudo apt-get update && sudo apt-get install libgtk-3-dev,
            build_command: cargo build --release,
            artifact_name: "clock-ubuntu",
            artifact_path: "clock"
          }
          - {
            os: macos-latest,
            command: brew install gtk+3,
            build_command: cargo bundle --release,
            artifact_name: "clock-macos",
            artifact_path: "bundle/osx"
          }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GTK
        if: matrix.platform.os != 'windows-latest'
        run: ${{ matrix.platform.command }}

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-bundle
        if: matrix.platform.os == 'macos-latest'
        run: cargo install cargo-bundle

      - name: Build artifact
        run: ${{ matrix.platform.build_command }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform.artifact_name}}
          path: "target/release/${{matrix.platform.artifact_path}}"
