name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "1-github-actions-for-running-tests-and-building-the-app"
  pull_request:
    branches:
      - "**"
      - "1-github-actions-for-running-tests-and-building-the-app"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run clippy
        run: cargo clippy --verbose

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
